### ISSUE TITLE
Floating TOC Overlapping Code Blocks and Images

### ISSUE THREAD

**Issue by jixianyan** [osmium-blog/osmium#11]
The floating TOC is causing an issue where it overlaps with the main content, specifically with code blocks and images.

<img width="781" alt="image" src="https://user-images.githubusercontent.com/45987126/230821763-e8c06d06-10cd-446f-89b3-1d24366944a5.png">
<img width="685" alt="image" src="https://user-images.githubusercontent.com/45987126/230821467-4ab7ddd7-93d0-4f6b-aaf0-d6aa955b2a5e.png">

**Comment by SilentDepth** [comment]
If you make the image a banner (stretched to page width), then TOC will overlap the image. This is an intended behavior since the TOC needs some space and the image needs to be fully spanned.

But code blocks should not and cannot be banners. Could you provide a reproduction?

**Comment by jixianyan** [comment]
So that means if I reduce the width of the image, will it solve the issue?

[This link](https://jixian-blog.vercel.app/wsl2-use-windows-proxy) can reproduce the issue with code blocks.

**Comment by jixianyan** [comment]
> If you make the image a banner (stretched to page width), then TOC will overlap the image. This is an intended behavior since the TOC needs some space and the image needs to be fully spanned.
> 
> But code blocks should not and cannot be banners. Could you provide a reproduction?

So that means if I reduce the width of the image, will it solve the issue?

[This link](https://jixian-blog.vercel.app/wsl2-use-windows-proxy) can reproduce the issue with code blocks.

**Comment by SilentDepth** [comment]
Well, this is not what I expected. I’ll mark it as a bug and fix it in v1.0.5.

However, I didn’t notice the image issue. Could you also provide a reproduction of that?

**Comment by jixianyan** [comment]
I just discovered that after stopping the use of Cusids, the previous issue I mentioned is no longer present, but a new issue has emerged where the images are not displayed completely.

<img width="1290" alt="image" src="https://user-images.githubusercontent.com/45987126/230914780-05b7855d-b941-4db3-ac77-9223a48ae3e5.png">
Please refer to [this page](https://jixian-blog.vercel.app/wsl2-use-windows-proxy)

**Comment by jixianyan** [comment]
I just discovered that after stopping the use of Cusdis, the previous issue I mentioned is no longer present, but a new issue has emerged where the images are not displayed completely.

<img width="1290" alt="image" src="https://user-images.githubusercontent.com/45987126/230915976-ef693084-be79-4582-aaff-9f56f6f66212.png">


Please refer to [this page](https://jixian-blog.vercel.app/wsl2-use-windows-proxy)
