### ISSUE TITLE
【问题反馈】非full page和full page图片展示逻辑不同

### ISSUE THREAD

**Issue by fishpigbird** [osmium-blog/osmium#7]
非full page下图片和Notion内显示一致，会横跨屏幕：
https://blog.fpb.icu/test-suHyZV223pc3Nr
![image](https://user-images.githubusercontent.com/128216091/230596316-7651c9b6-0c52-4545-9a5e-8125ea6c3cb3.png)
fullpage下，反而不会横跨屏幕
https://blog.fpb.icu/test-suHyZV223pc3Nr14
![image](https://user-images.githubusercontent.com/128216091/230597071-2f2320e4-96ff-46c2-b0b9-91f2c79f1513.png)

**Comment by SilentDepth** [comment]
Duplicated with #5
